env: "local" #окружение, в котором запущен проект. от него зависит поведение логов. в режиме prod пишется в файл, в local отображаются в консоли
log_file_path: "./logs/go_template.log"  #путь для хранения логов
allowed_file_extensions: ".pdf" #разрешенные расширения файлов - .pdf, .docx и т.п. разделитель - ;
max_file_size: 20 #максимальный разрешенный размер файла в мб
storage_path: "./storage"
jwt_secret: "" #соль для генерации jwt токена
max_request_size: 256
files_storage_path: "./var/uploads" ##место куда файлы будут складываться(если на бэке этом надо)
http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
db_server:  #параметры для соединения с базой данных
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "root"
  db_name: ""
smtp_server: #параметры smtp клиента для отправки сообщений на почту
  host: "
  port: 465
  username: "...@kst-energo.ru"
  password: ""
  sender: ""
frontend:
  app_url: "http://localhost:5173" #адрес(домен) фронтенда.
