env: "local" #окружение, в котором запущен проект. от него зависит поведение логов. в режиме prod пишется в файл, в local отображаются в консоли
log_file_path: "./logs/metrika.log"  #путь для хранения логов
jwt_secret: "" #соль для генерации jwt токена
max_request_size: 256
http_server:
  address: ":8080"
  timeout: 4s
  idle_timeout: 60s
db_server:  #параметры для соединения с базой данных
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "root"
  db_name: ""
frontend:
  app_url: "http://localhost:5173" #адрес(домен) фронтенда.
